# Generated by Django 4.0.6 on 2022-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('td', 'to-do'), ('ip', 'in-process'), ('f', 'finished')], default='td', max_length=2),
        ),
    ]
