# Generated by Django 4.0.6 on 2022-08-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_created_todo_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Status',
        ),
    ]
