# Generated by Django 3.2.14 on 2022-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Status_Choices',
            field=models.CharField(choices=[('do', 'Doing'), ('F', 'Finish'), ('ns', 'NotStarted')], default='ns', max_length=2),
        ),
    ]
